# Generated by Django 2.1.5 on 2019-03-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_auto_20190210_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementgroup',
            name='date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
