# Generated by Django 2.1.5 on 2019-03-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0003_measurementgroup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementgroup',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
