# Generated by Django 2.1.5 on 2019-03-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0004_measurementgroup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementrecording',
            name='number',
        ),
    ]
