# Generated by Django 2.2.2 on 2019-06-14 20:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nominal_power', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('commissioning_date', models.DateField()),
                ('feed_in_tariff', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('inverter_type', models.CharField(default='unknown', max_length=100)),
                ('pv_technology', models.CharField(default='unknown', max_length=100)),
                ('system_losses', models.FloatField(default=14.0)),
                ('mounting', models.CharField(default='fixed', max_length=100)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(-15.0), django.core.validators.MaxValueValidator(40.0)])),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(26.0), django.core.validators.MaxValueValidator(72.0)])),
                ('annual_energy_yield', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.IntegerField()),
                ('sub_component', models.IntegerField()),
                ('spot', models.CharField(max_length=250)),
                ('performance_losses_mean', models.FloatField()),
                ('performance_losses_sigma', models.FloatField()),
                ('percentage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ecfl', models.FloatField(default=0, editable=False)),
                ('ecfl_y', models.FloatField(default=0, editable=False)),
                ('ecfr', models.FloatField(default=0, editable=False)),
                ('time_before_detect', models.FloatField(default=0.99999, editable=False)),
                ('performance_losses', models.FloatField(default=1e-05, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='failures.Plant')),
            ],
        ),
    ]
