# Generated by Django 2.2.2 on 2019-06-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('failures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failure',
            name='ecfl',
        ),
        migrations.RemoveField(
            model_name='failure',
            name='ecfr',
        ),
        migrations.RemoveField(
            model_name='failure',
            name='performance_losses',
        ),
        migrations.RemoveField(
            model_name='failure',
            name='time_before_detect',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='inverter_type',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='mounting',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='pv_technology',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='system_losses',
        ),
    ]
