# Generated by Django 2.2.2 on 2019-06-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('failures', '0002_auto_20190615_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='failure',
            old_name='spot',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='failure',
            name='component',
        ),
        migrations.RemoveField(
            model_name='failure',
            name='sub_component',
        ),
    ]
