export const subComponents = [
  { name: "Backsheet", id: 1, component: 1 },
  { name: "Rear side glass", id: 2, component: 1 },
  { name: "Wires", id: 3, component: 1 },
  { name: "Connectors", id: 4, component: 1 },
  { name: "Juction Box", id: 5, component: 1 },
  { name: "Frame", id: 6, component: 1 },
  { name: "Glass", id: 7, component: 1 },
  { name: "Busbars", id: 9, component: 1 },
  { name: "Miscellaneous", id: 12, component: 1 },
  { name: "PV cell", id: 14, component: 1 },
  { name: "Connectors", id: 15, component: 2 },
  { name: "Installation", id: 16, component: 9 },
  { name: "Type", id: 17, component: 9 },
  { name: "Installation", id: 18, component: 2 },
  { name: "Crimpings", id: 19, component: 2 },
  { name: "Miscellaneous", id: 20, component: 2 },
  { name: "Integrity", id: 21, component: 2 },
  { name: "Enclosure", id: 22, component: 3 },
  { name: "Surge protection devices", id: 23, component: 3 },
  { name: "Cable glands", id: 24, component: 3 },
  { name: "Connectors", id: 25, component: 3 },
  { name: "Fuse holders", id: 26, component: 3 },
  { name: "Terminals", id: 27, component: 3 },
  { name: "Sealing caps", id: 28, component: 3 },
  { name: "Circuit breakers", id: 29, component: 3 },
  { name: "String monitoring", id: 30, component: 3 },
  { name: "Direct contact protection", id: 31, component: 3 },
  { name: "Miscellaneous", id: 32, component: 3 },
  { name: "String fuses", id: 34, component: 3 },
  { name: "Mounting", id: 36, component: 3 },
  { name: "Cable ducts", id: 37, component: 5 },
  { name: "Identification tags", id: 38, component: 5 },
  { name: "Juction Boxes", id: 40, component: 14 },
  { name: "Inverter monitoring", id: 41, component: 14 },
  { name: "String monitoring", id: 42, component: 14 },
  { name: "Entrance", id: 43, component: 13 },
  { name: "Fence", id: 44, component: 13 },
  { name: "Vegetation", id: 45, component: 13 },
  { name: "Manholes", id: 46, component: 13 },
  { name: "Paths", id: 47, component: 13 },
  { name: "Drainage System", id: 48, component: 13 },
  { name: "Miscellaneous", id: 49, component: 13 },
  { name: "Soil", id: 50, component: 13 },
  { name: "Trenches", id: 51, component: 13 },
  { name: "Direct contact protection", id: 53, component: 6 },
  { name: "Connectors", id: 54, component: 6 },
  { name: "Cable glands", id: 55, component: 6 },
  { name: "Enclosure", id: 56, component: 6 },
  { name: "Miscellaneous", id: 58, component: 6 },
  { name: "Mounting", id: 59, component: 6 },
  { name: "Sealing caps", id: 60, component: 6 },
  { name: "Circuit breakers", id: 61, component: 6 },
  { name: "Inverter monitoring", id: 62, component: 6 },
  { name: "Terminals", id: 63, component: 6 },
  { name: "Inverter fuses", id: 64, component: 6 },
  { name: "Surge protection devices", id: 65, component: 6 },
  { name: "Identification Tags", id: 66, component: 2 },
  { name: "Insulation", id: 67, component: 5 },
  { name: "Insulation", id: 68, component: 9 },
  { name: "Cable glands", id: 69, component: 12 },
  { name: "Connectors", id: 70, component: 12 },
  { name: "Direct contact protection", id: 71, component: 12 },
  { name: "Enclosure", id: 72, component: 12 },
  { name: "Identification tags", id: 73, component: 6 },
  { name: "Identification tags", id: 75, component: 12 },
  { name: "Identification Tags", id: 76, component: 3 },
  { name: "Miscellaneous", id: 77, component: 12 },
  { name: "Sealing caps", id: 78, component: 12 },
  { name: "Surge protection devices", id: 79, component: 12 },
  { name: "Terminals", id: 80, component: 12 },
  { name: "Fuses", id: 81, component: 12 },
  { name: "Circuit breakers", id: 82, component: 12 },
  { name: "Irradiation sensors", id: 83, component: 16 },
  { name: "Module temperature sensors", id: 84, component: 16 },
  { name: "PV module temperature sensors", id: 85, component: 14 },
  { name: "Irradiation sensors", id: 86, component: 14 },
  { name: "Enclosure", id: 87, component: 4 },
  { name: "Miscellaneous", id: 88, component: 4 },
  { name: "Terminals", id: 89, component: 4 },
  { name: "Surge protection devices", id: 90, component: 4 },
  { name: "Fuses", id: 91, component: 4 },
  { name: "Cable glands", id: 92, component: 4 },
  { name: "Connectors", id: 93, component: 4 },
  { name: "Circuit Breakers", id: 95, component: 4 },
  { name: "Direct contact protection", id: 96, component: 4 },
  { name: "Identification tags", id: 97, component: 4 },
  { name: "Mounting", id: 98, component: 4 },
  { name: "Firmware", id: 99, component: 4 },
  { name: "Fan", id: 100, component: 4 },
  { name: "UPS", id: 101, component: 18 },
  { name: "Emergency Generators", id: 102, component: 18 },
  { name: "Integrity", id: 103, component: 9 },
  { name: "Identification Tags", id: 104, component: 9 },
  { name: "Communication boards", id: 105, component: 14 },
  { name: "Dataloggers", id: 106, component: 14 },
  { name: "Fire detection system", id: 107, component: 14 },
  { name: "Ventilation", id: 108, component: 7 },
  { name: "Circuit breakers", id: 109, component: 7 },
  { name: "Panels", id: 112, component: 7 },
  { name: "Insulators", id: 114, component: 7 },
  { name: "Identification tags", id: 116, component: 7 },
  { name: "Enclosure", id: 118, component: 7 },
  { name: "Miscellaneous", id: 120, component: 7 },
  { name: "Room", id: 127, component: 7 },
  { name: "Intrusion system", id: 135, component: 14 },
  { name: "Lightning Protection", id: 136, component: 17 },
  { name: "Sensors", id: 137, component: 8 },
  { name: "Miscellaneous", id: 141, component: 8 },
  { name: "Integrity", id: 142, component: 1 },
  { name: "Identification tags", id: 144, component: 14 },
  { name: "Event messages", id: 148, component: 4 },
  { name: "Cable ducts", id: 149, component: 2 },
  { name: "Connectors", id: 150, component: 5 },
  { name: "Crimpings", id: 151, component: 5 },
  { name: "Miscellaneous", id: 152, component: 5 },
  { name: "Ties", id: 153, component: 5 },
  { name: "Type", id: 154, component: 5 },
  { name: "Installation", id: 155, component: 5 },
  { name: "Integrity", id: 156, component: 5 },
  { name: "Cable ducts", id: 157, component: 9 },
  { name: "Connectors", id: 158, component: 9 },
  { name: "Crimpings", id: 159, component: 9 },
  { name: "Insulation", id: 160, component: 2 },
  { name: "Miscellaneous", id: 161, component: 9 },
  { name: "Ties", id: 162, component: 2 },
  { name: "Type", id: 163, component: 2 },
  { name: "Ties", id: 164, component: 9 },
  { name: "Mounting", id: 165, component: 12 },
  { name: "Conductors", id: 167, component: 7 },
  { name: "Integrity", id: 170, component: 15 },
  { name: "Pillar", id: 171, component: 15 },
  { name: "Rafter", id: 172, component: 15 },
  { name: "Purlin", id: 173, component: 15 },
  { name: "Bracing pipe", id: 174, component: 15 },
  { name: "Clamps", id: 175, component: 15 },
  { name: "Other", id: 178, component: 17 },
  { name: "Bolts", id: 179, component: 15 },
  { name: "Solar Modules", id: 180, component: 15 },
  { name: "Miscellaneous", id: 181, component: 15 },
  { name: "Windings", id: 182, component: 8 },
  { name: "Bushes", id: 183, component: 8 },
  { name: "Tap changer", id: 184, component: 8 },
  { name: "Core", id: 185, component: 8 },
  { name: "Tank", id: 186, component: 8 },
  { name: "Protection system", id: 187, component: 8 },
  { name: "Cooling system", id: 188, component: 8 },
  { name: "Cable glands", id: 189, component: 7 },
  { name: "Connectors", id: 190, component: 7 },
  { name: "Direct contact protection", id: 191, component: 7 }
];
