export const SET_AUTH_STATUS = "SET_AUTH_STATUS";
export const SET_GROUPS = "SET_GROUPS";
export const ADD_GROUP = "ADD_GROUP";
export const REMOVE_GROUP = "REMOVE_GROUP";
export const SET_CURRENT_GROUP = "SET_CURRENT_GROUP";

export const SET_RECORDINGS = "SET_RECORDINGS";
export const ADD_RECORDING = "ADD_RECORDING";
export const REMOVE_RECORDING = "REMOVE_RECORDING";
export const SET_CURRENT_RECORDING = "SET_CURRENT_RECORDING";

export const SET_PLANTS = "SET_PLANTS";
export const ADD_PLANT = "ADD_PLANT";
export const REMOVE_PLANT = "REMOVE_PLANT";
export const SET_CURRENT_PLANT = "SET_CURRENT_PLANT";
export const SET_CURRENT_FAILURES_PLANT = "SET_CURRENT_FAILURES_PLANT";

export const SET_FAILURES = "SET_FAILURES";
export const ADD_FAILURE = "ADD_FAILURE";
export const REMOVE_FAILURE = "REMOVE_FAILURE";
export const SET_CURRENT_FAILURE = "SET_CURRENT_FAILURE";
